#!docker-compose.yml

services:
  nginx-ssl-proxy:
    image: wezell/nginx-letsencrypt-proxy
    restart: always
    environment:
      UPSTREAM: 127.0.0.1:8080
      SERVERNAME: test.example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
